import type { NextPage } from "next";
import Head from "next/head";
import Hero from "./Hero";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Christian Villamin&apos;s personal website.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Hero />
      </section>

      <footer />
    </div>
  );
};

export default Home;
