import type { NextPage } from "next";
import Head from "next/head";
import Hero from "./Hero";
import Blogs from "./Blogs";
import Stack from "./Stack";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Christian Villamin&apos;s personal website.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="max-w-3xl mx-auto">
        <Hero />
        <div>
          <h1 className="text-center mt-8">Work in Progress ! ! !</h1>
        </div>
        <Blogs />
        <Stack />
      </section>

      <footer />
    </div>
  );
};

export default Home;
