import "./global.css";
import Layout from "./(layout)/Layout";

// const Layout = ({ children }: any) => {
//   return (
//     <div className="min-h-screen flex flex-col">
//       <main className="flex-grow max-w-3xl mx-auto md:pt-12">{children}</main>
//     </div>
//   );
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Christian Villamin&apos; Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
