import Hero from "./Hero";
import Blogs from "./Blogs";
import Stack from "./Stack";
import Projects from "./Project";

const Home = () => {
  return (
    <div>
      {/* <Head>
        <title>Christian Villamin&apos;s personal website.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <section className="max-w-3xl mx-auto">
        <Hero />

        <div className="px-4">
          <div>
            <h1 className="text-center mt-4">
              My personal slice of the internet.
            </h1>
          </div>
          <Blogs />
          <Stack />
          <Projects />
        </div>
      </section>

      <footer />
    </div>
  );
};

export default Home;
